### ISSUE TITLE
[OS 8 RC] Some Flatpaks do not have icons, falls back to Purple Star icon

### ISSUE THREAD

**Issue by cyrneko** [elementary/triage#584]
### What Happened?

In the current elementaryOS 8 release-candidate / build with stable repos, some installed Flatpaks do not show their corresponding icons, whilst some others do.

Some apps that are lacking their icons:
- [Fractal](https://flathub.org/apps/org.gnome.Fractal)
- [Gear Lever](https://flathub.org/apps/it.mijorus.gearlever)
- [Resources](https://flathub.org/apps/net.nokyan.Resources)
- [SyncThingy](https://flathub.org/apps/com.github.zocker_160.SyncThingy)

Some apps that are *not* lacking their icons:
- All the included io.elementary.* apps
- [Vesktop](https://flathub.org/apps/dev.vencord.Vesktop)
- [Signal Desktop](https://flathub.org/apps/org.signal.Signal)
- [Zen browser](https://flathub.org/apps/io.github.zen_browser.zen)
- [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal)

The icons are missing *everywhere* in the OS, including [gala](https://github.com/elementary/gala), [applications menu](https://github.com/elementary/applications-menu), [dock](https://github.com/elementary/dock) (not plank), and the [settings/switchboard](https://github.com/elementary/switchboard).

This behavior persists across reboots, OS installations, Flatpak re-installs of affected apps, and when re-generating the icon cache using `# gtk-update-icon-cache --verbose /usr/share/icons/elementary`

### Steps to Reproduce

1. Install a flatpak app (preferably one of the known affected ones)
2. Wait for it to appear in different parts of the OS
3. See bug, icon is not available.

### Expected Behavior

The respective application's icon should be used to represent it.

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by cyrneko** [comment]
Update:

Previously I said:
> and when re-generating the icon cache using `# gtk-update-icon-cache --verbose /usr/share/icons/elementary`

However, it turns out that Flatpak (or the OS?) runs a different job when flatpaks are installed, so installing one Flatpak and having it re-generate icons has a high chance of fixing *previously broken Flatpaks*

E.g I have fixed all of the above icons by simply installing any random flatpak, e.g the AHSPD Portals demo, and having it regenerate the cache that way.

A restart of affected components, e.g io.elementary.wingpanel or io.elementary.dock may still be required, but that seems rare and an edge-case.

**Comment by teamcons** [comment]
The issue seem a bit random, but i can definitively reproduce

Terminal, Switchboard, Feedback are missing theirs
Flatseal, Resource, are not missing
Monitors, missing. I recall on my previous 8 Install, it did have it.

**Comment by cyrneko** [comment]
> The issue seem a bit random, but i can definitively reproduce
> 
> Terminal, Switchboard, Feedback are missing theirs Flatseal, Resource, are not missing Monitors, missing. I recall on my previous 8 Install, it did have it.

thanks for verifying this is not just a broken build/ISO on my end :)

**Comment by teamcons** [comment]
OH SORRY Cyrneko im so sorry, I forgot to mention (i thought this was about Gala...) in my case it is only Gala.
I jumped in and thought it was https://github.com/elementary/gala/issues/2067 (closed but still present), which is why i didnt react much earlier at your issue, i thought it would be marked as duplicate.

Appmenu and Dock show correctly for me. Both issues may be linked - The only difference between your builds and the official ISO is that the issue is more widely present on your side. But it looks eerily similar, and behave much the same way.

Somehow, since, the last apt update fixed the purple icon for the switchboard. In the same way that installing a flatpak may fix the icon issue for a flatpak app

**Comment by lenemter** [comment]
Can't reproduce this issue. I suppose it got fixed in https://github.com/elementary/gala/pull/2382
